server:
  address: 192.168.17.83   # LAN内の他端末からもアクセスしたいとき
  port: 7777
  servlet:
    context-path: /efoot

spring:
  thymeleaf:
    cache: false     # 開発中は false が便利
  jpa:
    hibernate:
      ddl-auto: update   # 開発中のみ。既存DBがあるなら validate 推奨
  datasource:
    url: jdbc:mysql://localhost:3306/efoot?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Tokyo
    username: root
    password: your_password
