server:
  port: ${PORT:8080}
  servlet:
    context-path: /efoot   # 直下で出したいなら "/" に

spring:
  datasource:
    url: ${JDBC_URL:jdbc:h2:mem:efoot;MODE=MySQL}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
