server:
  servlet:
    context-path: /efoot

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/${DB_NAME:efoot}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update          # 初回は update/create でも可
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
