server:
  port: ${PORT:8080}
  servlet:
    context-path: /efoot   # すでに使っているならそのまま

spring:
  datasource:
    url: ${JDBC_URL:}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
logging:
  level:
    org.hibernate.SQL: warn
